# Generated by Django 6.0.1 on 2026-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soar_quiz_average_score',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
