# Generated by Django 6.0.1 on 2026-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_soar_quiz_average_score_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soar_quiz_average_score',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
