# Generated by Django 6.0.1 on 2026-02-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_soar_quiz_average_score_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailoruser',
            name='address',
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='Gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sailoruser',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
