# Generated by Django 6.0.1 on 2026-02-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sailoruser_address_sailoruser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sailoruser',
            name='reset_password_token',
        ),
    ]
