# Generated by Django 6.0.1 on 2026-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_sailoruser_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='hobbies',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
