# Generated by Django 6.0.1 on 2026-02-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sailoruser_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
