# Generated by Django 6.0.1 on 2026-02-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sailoruser_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.ImageField(default=1, upload_to='banner_images/'),
            preserve_default=False,
        ),
    ]
