# Generated by Django 6.0.1 on 2026-02-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
