# Generated by Django 6.0.1 on 2026-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_category_course_module_docs_contents_video_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
