# Generated by Django 6.0.1 on 2026-02-14 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sailoruser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_time', models.TimeField()),
                ('type', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.video_contents')),
            ],
        ),
    ]
