# Generated by Django 6.0.1 on 2026-02-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_video_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='mobile_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
