# Generated by Django 6.0.1 on 2026-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_soar_quiz_average_score_sailoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='soar_quiz_answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
