# Generated by Django 6.0.1 on 2026-02-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_soar_quiz_answer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='soar_quiz_answer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='api.soar_category'),
            preserve_default=False,
        ),
    ]
