# Generated by Django 6.0.1 on 2026-02-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_soar_quiz_answer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soar_quiz_answer',
            old_name='SailorUser',
            new_name='email',
        ),
    ]
