# Generated by Django 6.0.1 on 2026-02-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_sailoruser_soar_quiz_answer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soar_quiz_answer',
            old_name='email',
            new_name='SailorUser',
        ),
    ]
