# Generated by Django 6.0.1 on 2026-02-18 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_email_soar_quiz_answer_sailoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
