# Generated by Django 6.0.1 on 2026-02-18 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_sailoruser_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sailoruser',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
