# Generated by Django 6.0.1 on 2026-02-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_sailoruser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sailoruser',
            name='reset_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
